# Generated by Django 4.2 on 2023-04-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='prodapp',
        ),
        migrations.AddField(
            model_name='product',
            name='product_in_stock',
            field=models.IntegerField(default=0),
        ),
    ]
