# Generated by Django 4.2 on 2023-04-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_product_product_image_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='default_image.jpg', upload_to='product'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
