# Generated by Django 4.2 on 2023-04-13 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_product_product_image_delete_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('phone', models.IntegerField(default=9999999999)),
                ('zipcode', models.IntegerField(default=1234)),
                ('region', models.CharField(choices=[('ER', 'Eastern Region'), ('GA', 'Greater Accra'), ('AH', 'Ahafo Region'), ('AS', 'Ashanti'), ('BE', 'Bono East'), ('BA', 'Brong Ahafo'), ('CE', 'Central Region'), ('NE', 'North East'), ('NO', 'Northern'), ('OT', 'Oti Region'), ('SA', 'Savannah Region'), ('UE', 'Upper East'), ('UW', 'Upper West'), ('WE', 'Western Region'), ('WN', 'Western North'), ('VO', 'Volta Region')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
