# Generated by Django 4.2 on 2023-04-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='region',
            field=models.CharField(choices=[('Eastern Region', 'Eastern Region'), ('Greater Accra', 'Greater Accra'), ('Ahafo Region', 'Ahafo Region'), ('Ashanti', 'Ashanti'), ('Bono East', 'Bono East'), ('Brong Ahafo', 'Brong Ahafo'), ('Central Region', 'Central Region'), ('North East', 'North East'), ('Northern', 'Northern'), ('Oti Region', 'Oti Region'), ('Savannah Region', 'Savannah Region'), ('Upper East', 'Upper East'), ('Upper West', 'Upper West'), ('Western Region', 'Western Region'), ('Western North', 'Western North'), ('Volta Region', 'Volta Region')], max_length=100),
        ),
    ]
