# Generated by Django 4.2 on 2023-04-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_payment_orderplaced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('AP', 'Apple'), ('LE', 'Lenovo'), ('HP', 'Hp'), ('DL', 'Dell'), ('Acer', 'Acer'), ('Toshiba', 'Toshiba'), ('Asus', 'Asus'), ('MS', 'Microsoft Laptop')], max_length=10),
        ),
    ]
