# Generated by Django 4.2 on 2023-04-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='about_the_device',
            field=models.TextField(default=''),
        ),
    ]
