# Generated by Django 4.2 on 2023-04-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_product_about_the_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='note',
            field=models.TextField(default=''),
        ),
    ]
